[project]
name = "tiny-moe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.1"
dependencies = [
    "flax>=0.11.1",
    "jax>=0.7.0",
    "transformers>=4.55.0",
]
